// react-app/src/components/TestDirective.tsx
import { version } from 'react';

/**
 * Port of Angular's `TestDirectiveComponent` (`app-test-directive`).
 * Logs on construction and displays the framework version. Declared but not
 * rendered in the page (matches the Angular module).
 */
export default function TestDirective() {
  console.info('test-directive initialized...');

  return (
    <div data-testid="react-version-directive" className="test-directive">
      React Version: {version}
    </div>
  );
}

// src/app/components/test-directive/test-directive.component.ts
import { Component, VERSION } from '@angular/core';

@Component({
  selector: 'app-test-directive',
  standalone: true,
  template: `<div data-testid="angular-version-directive" class="test-directive">Angular Version: {{ version }}</div>`
})
export class TestDirectiveComponent {
  version = VERSION.full;

  constructor() {
    console.info('test-directive initialized...');
  }
}
